---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: 'Vous pouvez ajouter une image ONTAP Select à votre instance de l"utilitaire d"administration Deploy. Une fois l"image installée, vous pouvez l"utiliser lors du déploiement d"un cluster ONTAP Select .' 
---
= Ajouter une image ONTAP Select à déployer
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez ajouter une image ONTAP Select à votre instance de l'utilitaire d'administration Deploy. Une fois l'image installée, vous pouvez l'utiliser lors du déploiement d'un cluster ONTAP Select .



== Avant de commencer

À un niveau élevé, le processus utilisé pour ajouter une image ONTAP Select à une instance de Deploy se compose de quatre étapes :

. Téléchargement de l'image d'installation
. Téléchargement de l'image d'installation sur la machine virtuelle Deploy
. Ajout de l'image d'installation
. Affichage des images d'installation disponibles


Avant d’ajouter de nouvelles images ONTAP Select à déployer, vous devez d’abord supprimer toutes les images inutiles.


NOTE: Vous ne devez ajouter qu'une image ONTAP Select dont la version est antérieure à la version d'origine fournie avec votre instance de l'utilitaire Deploy. L'ajout de versions ultérieures d' ONTAP Select dès leur mise à disposition par NetApp n'est pas pris en charge.



== Téléchargez l'image d'installation

Pour commencer le processus d'ajout d'une image ONTAP Select à une instance de l'utilitaire Deploy, vous devez télécharger l'image d'installation depuis le site de support NetApp . L'image d'installation ONTAP Select est formatée dans un fichier compressé unique.

.Étapes
. Accédez au site de support NetApp à l'aide d'un navigateur Web et cliquez sur *Liens rapides de support*.
. Cliquez sur *Télécharger le logiciel* sous *Tâches principales* et connectez-vous au site.
. Cliquez sur *Trouver votre produit*.
. Faites défiler vers le bas et cliquez sur * ONTAP Select*.
. Sous *Autres logiciels disponibles*, cliquez sur *Déployer la mise à niveau, Mise à niveau du nœud, Installation de l'image*.
. Sélectionnez la version souhaitée du package de mise à niveau.
. Consultez le contrat de licence utilisateur final (CLUF) et cliquez sur *Accepter et continuer*.
. Sélectionnez et téléchargez le package approprié, en répondant à toutes les invites selon les besoins de votre environnement.




== Téléchargez l'image d'installation sur Deploy

Après avoir acquis l’image d’installation ONTAP Select , vous devez télécharger le fichier sur la machine virtuelle Deploy.

.Avant de commencer
Vous devez disposer du fichier image d'installation sur votre poste de travail local. Vous devez également connaître le mot de passe du compte administrateur Deploy.

.À propos de cette tâche
Cette tâche décrit une méthode de téléchargement du fichier sur la machine virtuelle Deploy. D'autres options peuvent être plus adaptées à votre environnement.

.Étape
. Dans un shell de commande sur votre poste de travail local, téléchargez le fichier image sur la machine virtuelle Deploy.
+
Exemple

+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
Exemple

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.Résultat
Le fichier d'installation du nœud est stocké dans le répertoire personnel de l'utilisateur administrateur.



== Ajouter l'image d'installation

Vous pouvez ajouter l’image d’installation ONTAP Select au répertoire des images de déploiement afin qu’elle soit disponible lors du déploiement d’un nouveau cluster.

.Avant de commencer
Vous devez connaître le répertoire dans lequel se trouve le fichier image d'installation sur la machine virtuelle de l'utilitaire de déploiement. Le fichier est supposé se trouver dans le répertoire personnel de l'administrateur.

.Étapes
. Sign in à l'interface de ligne de commande de l'utilitaire de déploiement à l'aide de SSH avec le compte administrateur (admin).
. Démarrez le shell Bash :
+
`shell bash`

. Placez le fichier image d’installation dans le répertoire images.
+
Exemple 
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== Afficher les images d'installation disponibles

Vous pouvez afficher les images ONTAP Select disponibles lors du déploiement d'un nouveau cluster.

.Étapes
. Accédez à la page Web de documentation en ligne sur la machine virtuelle de l'utilitaire de déploiement et connectez-vous à l'aide du compte administrateur (admin) :
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
Utilisez le nom de domaine ou l’adresse IP de la machine virtuelle de déploiement.

. Accédez au bas de la page et cliquez sur *Déployer*, puis sur *OBTENIR /images*.
. Cliquez sur *Essayer !* pour afficher les images ONTAP Select disponibles.
. Confirmez que l’image souhaitée est disponible.

