---
sidebar: sidebar 
permalink: task_cluster_expansion_contraction.html 
keywords: cluster, expand, expansion, contract, contraction, six, eight, node deployment workflow, workflow, deployment steps 
summary: 'À partir d" ONTAP Select 9.15.1, vous pouvez augmenter la taille d"un cluster existant de six à huit nœuds et réduire la taille du cluster de huit à six nœuds.' 
---
= Développer ou réduire un cluster ONTAP Select
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
À partir d' ONTAP Select 9.15.1, vous pouvez augmenter la taille d'un cluster existant de six à huit nœuds et réduire la taille du cluster de huit à six nœuds.

Les extensions et contractions de cluster suivantes ne sont pas prises en charge :

* Extensions de clusters à un, deux ou quatre nœuds vers des clusters à six ou huit nœuds.
* Contractions de clusters à six ou huit nœuds vers des clusters à un, deux ou quatre nœuds.


[NOTE]
====
Pour modifier le nombre de nœuds d'un cluster à une taille qui n'est pas prise en charge par l'extension ou la contraction du cluster, vous devez effectuer les tâches suivantes :

. Déployez un nouveau cluster multi-nœuds en utilisant le link:task_cli_deploy_cluster.html["CLI"] ou le link:task_deploy_cluster.html["interface Web"] fourni avec l'utilitaire d'administration ONTAP Select Deploy.
. Le cas échéant, migrez les données vers le nouveau cluster en utilisant link:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html["Réplication SnapMirror"^] .


====
Vous lancez les procédures d’extension et de contraction du cluster à partir d’ ONTAP Select Deploy à l’aide de l’interface CLI, de l’API ou de l’interface Web.



== Considérations relatives au matériel et au stockage

Les fonctionnalités d'expansion et de contraction des clusters sont limitées des manières suivantes :

* La prise en charge est limitée aux clusters créés sur des hôtes hyperviseurs ESX. Les versions ESX suivantes sont compatibles avec ONTAP Select 9.15.1 et versions ultérieures :
+
** ESXi 8.0 U3
** ESXi 8.0 U2
** ESXi 8.0 U1
** ESXi 8.0 GA
** ESXi 7.0 U3
** ESXi 7.0






== Développer le cluster

Vous pouvez augmenter la taille d'un cluster existant d'un cluster à six nœuds à un cluster à huit nœuds avec la fonction d'extension de cluster.

.À propos de cette tâche
En préparation de la procédure d'extension du cluster, de nouveaux hôtes ESX sont ajoutés à l'inventaire et les détails des nouveaux nœuds sont attribués. Avant de lancer l'extension du cluster, une pré-vérification du réseau interne est effectuée.

.Avant de commencer
* Lors du déploiement d'un cluster multi-nœuds, vous devez vous familiariser avec le vérificateur de connectivité réseau. Vous pouvez l'exécuter à l'aide de l'outil link:task_adm_connectivity.html["interface Web"] ou le link:task_cli_connectivity.html["CLI"] .
* Vérifiez que vous disposez des détails de licence pour les nouveaux nœuds.


.Étapes
. Sign in à l’interface utilisateur Web de l’utilitaire de déploiement à l’aide du compte administrateur.
. Sélectionnez l’onglet *Cluster* en haut de la page et sélectionnez le cluster souhaité dans la liste.
. Sur la page des détails du cluster, sélectionnez l'icône d'engrenage à droite de la page et sélectionnez *Développer le cluster*.
. Accédez à la section *HA Pair 4*.
. Choisissez les détails de configuration de la paire haute disponibilité (HA) pour la quatrième paire HA, notamment :
+
** Type d'instance
** Noms de nœuds
** Hôtes hyperviseurs associés
** Adresses IP des nœuds
** Licences
** Configuration du réseau
** Configuration du stockage (type RAID et pools de stockage)


. Sélectionnez *Enregistrer la paire HA* pour enregistrer les détails de configuration.
. Fournissez les informations d’identification ONTAP , puis sélectionnez *Développer le cluster*.
. Sélectionnez *Suivant* et exécutez la pré-vérification du réseau en sélectionnant *Exécuter*.
+
La pré-vérification du réseau valide que le réseau interne sélectionné pour le trafic du cluster ONTAP fonctionne correctement.

. Sélectionnez *Développer le cluster* pour lancer le processus d’extension du cluster, puis sélectionnez *OK* dans la boîte de dialogue.
+
L’extension du cluster peut prendre jusqu’à 45 minutes.

. Surveillez le processus d’extension du cluster en plusieurs étapes pour confirmer que le cluster s’est étendu avec succès.
. Consultez l'onglet *Événements* pour des mises à jour régulières sur l'avancement de l'opération. La page est automatiquement actualisée à intervalles réguliers.


.Après avoir terminé
Après avoir étendu le cluster, vous devez sauvegarder les données de configuration ONTAP Select Deploy.



== Contracter le cluster

Vous pouvez réduire la taille d'un cluster existant d'un cluster de huit nœuds à un cluster de six nœuds avec la fonction de contraction de cluster.

.À propos de cette tâche
La paire de nœuds HA souhaitée dans le cluster est sélectionnée pour préparer la contraction du cluster pendant la procédure.

.Étapes
. Sign in à l’interface utilisateur Web de l’utilitaire de déploiement à l’aide du compte administrateur.
. Sélectionnez l’onglet *Cluster* en haut de la page et sélectionnez le cluster souhaité dans la liste.
. Sur la page des détails du cluster, sélectionnez l'icône d'engrenage à droite de la page, puis sélectionnez *Cluster de contrat*.
. Sélectionnez les détails de configuration de la paire HA pour toute paire HA que vous souhaitez supprimer et fournissez les informations d'identification ONTAP , puis sélectionnez *Contract Cluster*.
+
La contraction du cluster peut prendre jusqu’à 30 minutes.

. Surveillez le processus de contraction du cluster en plusieurs étapes pour confirmer que le cluster s'est contracté avec succès.
. Consultez l'onglet *Événements* pour des mises à jour régulières sur l'avancement de l'opération. La page est automatiquement actualisée à intervalles réguliers.

