---
sidebar: sidebar 
permalink: task_cli_deploy_recover_two_node.html 
keywords: administer, administering, cli, two node cluster, recover, recovering 
summary: 'Si l"utilitaire ONTAP Select Deploy échoue ou devient indisponible pour une raison quelconque, vous ne pouvez plus administrer les nœuds et clusters ONTAP Select . De plus, tous les clusters à deux nœuds perdent leur capacité de haute disponibilité, car le service de médiation inclus avec Deploy est indisponible. En cas de panne irrémédiable, vous devez restaurer l"instance de l"utilitaire Deploy pour restaurer les fonctionnalités d"administration et de haute disponibilité.' 
---
= Récupérer l'utilitaire ONTAP Select Deploy pour un cluster à deux nœuds
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si l'utilitaire ONTAP Select Deploy échoue ou devient indisponible pour une raison quelconque, vous ne pouvez plus administrer les nœuds et clusters ONTAP Select . De plus, tous les clusters à deux nœuds perdent leur capacité de haute disponibilité, car le service de médiation inclus avec Deploy est indisponible. En cas de panne irrémédiable, vous devez restaurer l'instance de l'utilitaire Deploy pour restaurer les fonctionnalités d'administration et de haute disponibilité.



== Avant de commencer

Vous devez vous préparer avant de tenter de récupérer une instance de l’utilitaire de déploiement pour garantir le succès.

.Compétences et informations requises
Vous devez être familier avec plusieurs procédures administratives et disposer des informations requises.

.Installation de la machine virtuelle Deploy
Vous devez pouvoir installer une nouvelle instance de l’utilitaire ONTAP Select Deploy dans votre environnement d’hyperviseur.

.Interface de ligne de commande ONTAP
Vous devez pouvoir vous connecter à l'interface de ligne de commande ONTAP du cluster ONTAP Select et utiliser l'interface shell.

.Disponibilité de la sauvegarde de la configuration de l'utilitaire de déploiement
Vous devez déterminer si vous disposez d'une sauvegarde des données de configuration de l'instance de l'utilitaire Deploy défaillante contenant le cluster à deux nœuds ONTAP Select . Il est possible que votre sauvegarde ne contienne pas le cluster.

.Restauration d'une sauvegarde de la configuration de déploiement
Vous devriez pouvoir restaurer une sauvegarde des données de configuration de déploiement, en fonction de la procédure de récupération utilisée.

.Adresse IP de la machine virtuelle de déploiement d'origine
Vous devez connaître l’adresse IP de la machine virtuelle de l’utilitaire de déploiement d’origine qui a échoué.

.Licences de capacité de stockage
Vous devez déterminer si vous utilisez une licence par pools de capacité ou par niveaux de capacité. Si vous utilisez une licence par pools de capacité, vous devez réinstaller chaque licence de pool de capacité après la récupération ou la restauration de l'instance Deploy.

.Déterminer quelle procédure de récupération utiliser
Vous devez choisir la procédure à suivre pour récupérer une instance de l'utilitaire ONTAP Select Deploy. Votre décision dépend de la présence ou non d'une sauvegarde des données de configuration de l'utilitaire Deploy d'origine, défaillant, contenant le cluster à deux nœuds ONTAP Select .

[cols="35,65"]
|===
| Avez-vous une sauvegarde de déploiement contenant le cluster à deux nœuds ? | Procédure de récupération à utiliser 


| Oui | Restaurer une instance de l'utilitaire Deploy à l'aide d'une sauvegarde de configuration 


| Non | Reconfigurer et récupérer une instance de l'utilitaire Deploy 
|===


== Restaurer une instance de l'utilitaire Deploy à l'aide d'une sauvegarde de configuration

Si vous disposez d'une sauvegarde de l'instance de l'utilitaire Deploy défaillante contenant le cluster à deux nœuds, vous pouvez restaurer les données de configuration sur la nouvelle instance de machine virtuelle Deploy. Vous devez ensuite terminer la récupération en effectuant une configuration supplémentaire des deux nœuds du cluster ONTAP Select .

.Avant de commencer
Vous devez disposer d'une sauvegarde des données de configuration de la machine virtuelle Deploy d'origine défaillante contenant le cluster à deux nœuds. Vous devez pouvoir vous connecter à l'interface de ligne de commande ONTAP du cluster à deux nœuds et connaître les noms ONTAP des deux nœuds.

.À propos de cette tâche
Étant donné que la sauvegarde de configuration que vous restaurez contient le cluster à deux nœuds, les cibles iSCSI et les boîtes aux lettres du médiateur sont recréées dans la nouvelle machine virtuelle de l'utilitaire de déploiement.

.Étapes
. Préparez une nouvelle instance de l'utilitaire ONTAP Select Deploy :
+
.. Installez une nouvelle machine virtuelle utilitaire de déploiement.
.. Restaurez la configuration de déploiement à partir d’une sauvegarde précédente sur la nouvelle machine virtuelle.
+
Reportez-vous aux tâches associées pour obtenir des informations plus détaillées sur les procédures d’installation et de restauration.



. Sign in à l'interface de ligne de commande ONTAP du cluster à deux nœuds ONTAP Select .
. Entrer en mode privilège avancé :
+
`set adv`

. Si l'adresse IP de la nouvelle machine virtuelle de déploiement est différente de celle de la machine virtuelle de déploiement d'origine, vous devez supprimer les anciennes cibles iSCSI du médiateur et ajouter de nouvelles cibles :
+
....
storage iscsi-initiator remove-target -node * -target-type mailbox

storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>

storage iscsi-initiator add-target -node <node2_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
....
+
Le  `<ip_address>` le paramètre est l'adresse IP de la nouvelle machine virtuelle de déploiement.

+
Ces commandes permettent aux nœuds ONTAP Select de découvrir les disques de boîte aux lettres sur la nouvelle machine virtuelle de l'utilitaire de déploiement.

. Déterminer les noms des disques médiateurs :
+
`disk show -container-type mediator`

. Affectez les disques de boîte aux lettres aux deux nœuds :
+
....
disk assign -disk <mediator-disk1-name> -owner <node1-name>
disk assign -disk <mediator-disk2-name> -owner <node2-name>
....
. Vérifiez que le basculement du stockage est activé :
+
`storage failover show`



.Après avoir terminé
Si vous utilisez des licences Capacity Pools, vous devez réinstaller chaque licence Capacity Pool. Pour plus d'informations, consultez la section « Réinstaller une licence Capacity Pool ».



== Reconfigurer et récupérer une instance de l'utilitaire Deploy

Si vous ne disposez pas d'une sauvegarde de l'instance défaillante de l'utilitaire Deploy contenant le cluster à deux nœuds, vous devez configurer la cible iSCSI du médiateur et la boîte aux lettres dans la nouvelle machine virtuelle Deploy. Vous devez ensuite terminer la récupération en effectuant une configuration supplémentaire des deux nœuds du cluster ONTAP Select .

.Avant de commencer
Vous devez connaître le nom de la cible du médiateur pour la nouvelle instance de l'utilitaire Deploy. Vous devez pouvoir vous connecter à l'interface de ligne de commande ONTAP du cluster à deux nœuds et connaître les noms ONTAP des deux nœuds.

.À propos de cette tâche
Vous pouvez éventuellement restaurer une sauvegarde de configuration sur la nouvelle machine virtuelle Deploy, même si elle ne contient pas le cluster à deux nœuds. Comme le cluster à deux nœuds n'est pas recréé lors de la restauration, vous devez ajouter manuellement la cible iSCSI du médiateur et la boîte aux lettres à la nouvelle instance de l'utilitaire Deploy via la page web de documentation en ligne d' ONTAP Select lors de l'installation de Deploy. Vous devez pouvoir vous connecter au cluster à deux nœuds et connaître les noms ONTAP des deux nœuds.


NOTE: L'objectif de la procédure de récupération est de restaurer le cluster à deux nœuds à un état sain, où les opérations normales de prise de contrôle et de restitution HA peuvent être effectuées.

.Étapes
. Préparez une nouvelle instance de l'utilitaire ONTAP Select Deploy :
+
.. Installez une nouvelle machine virtuelle utilitaire de déploiement.
.. Restaurez éventuellement la configuration de déploiement à partir d’une sauvegarde précédente sur la nouvelle machine virtuelle.
+
Si vous restaurez une sauvegarde précédente, la nouvelle instance Deploy ne contiendra pas le cluster à deux nœuds. Consultez la section d'informations associée pour plus d'informations sur les procédures d'installation et de restauration.



. Sign in à l'interface de ligne de commande ONTAP du cluster à deux nœuds ONTAP Select .
. Entrer en mode privilégié avancé :
+
`set adv`

. Obtenir le nom de la cible iSCSI du médiateur :
+
`storage iscsi-initiator show -target-type mailbox`

. Accédez à la page Web de documentation en ligne sur la nouvelle machine virtuelle de l'utilitaire de déploiement et connectez-vous à l'aide du compte administrateur :
+
`\http://<ip_address>/api/ui`

+
Vous devez utiliser l’adresse IP de votre machine virtuelle Deploy.

. Cliquez sur *Médiateur* puis sur *OBTENIR /médiateurs*.
. Cliquez sur *Essayer !* pour afficher une liste des médiateurs gérés par Deploy.
+
Notez l’ID de l’instance de médiateur souhaitée.

. Cliquez sur *Mediator* puis sur *POST*.
. Fournissez la valeur pour mediator_id.
. Cliquez sur le *Modèle* à côté de  `iscsi_target` et complétez la valeur du nom.
+
Utilisez le nom cible pour le paramètre iqn_name.

. Cliquez sur *Essayer !* pour créer la cible iSCSI du médiateur.
+
Si la demande réussit, vous recevrez le code d’état HTTP 200.

. Si l'adresse IP de la nouvelle machine virtuelle de déploiement est différente de celle de la machine virtuelle de déploiement d'origine, vous devez utiliser l'interface de ligne de commande ONTAP pour supprimer les anciennes cibles iSCSI du médiateur et ajouter de nouvelles cibles :
+
....
storage iscsi-initiator remove-target -node * -target-type mailbox

storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>

storage iscsi-initiator add-target -node <node2_name> -label mediator-target-type mailbox -target-portal <ip_address> -target-name <target>
....
+
Le  `<ip_address>` le paramètre est l'adresse IP de la nouvelle machine virtuelle de déploiement.



Ces commandes permettent aux nœuds ONTAP Select de découvrir les disques de boîte aux lettres sur la nouvelle machine virtuelle de l'utilitaire de déploiement.

. Déterminer les noms des disques médiateurs :
+
`disk show -container-type mediator`

. Affectez les disques de boîte aux lettres aux deux nœuds :
+
....
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
....
. Vérifiez que le basculement du stockage est activé :
+
`storage failover show`



.Après avoir terminé
Si vous utilisez des licences Capacity Pools, vous devez réinstaller chaque licence Capacity Pool. Pour plus d'informations, consultez la section « Réinstaller une licence Capacity Pool ».

.Informations connexes
* link:task_install_deploy.html["Installer ONTAP Select Deploy"]
* link:task_cli_migrate_deploy.html#restoring-the-deploy-configuration-data-to-the-new-virtual-machine["Restaurer les données de configuration de déploiement sur la nouvelle machine virtuelle"]
* link:task_adm_licenses.html#reinstalling-a-capacity-pool-license["Réinstaller une licence Capacity Pool"]

